[project]
name = "e7-shop-refresher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mss>=10.1.0",
    "numpy>=2.4.4",
    "opencv-contrib-python==4.13.0.92",
    "pyautogui==0.9.54",
    "pygetwindow>=0.0.9",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.pytest.ini_options]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
